version: "3.7"
services:
  splash:
    image: scrapinghub/splash
    expose:
      - 8050
      - 5023
    ports:
      - "8050:8050"
      - "5023:5023"
  mongo:
    image: mongo
    expose:
      - 27017
    ports:
      - "27017:27017"
    volumes:
      - /data/db
  update:
    build: ./cron
    depends_on:
      - splash
      - mongo
    volumes:
      - type: bind
        source: ./cron
        target: /usr/src/app
