version: "3"
services:
  splash:
    image: scrapinghub/splash
    ports:
      - 8050:8050
      - 5023:5023
  mongo:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - /data/db
  web:
    image: prakhar1989/foodtrucks-web
    command: python app.py
    depends_on:
      - es
    ports:
      - 5000:5000
    volumes:
      - ./flask-app:/opt/flask-app
volumes:
    esdata1:
      driver: local
